### ISSUE TITLE
No additional $_GET parameters on routed controllers

### ISSUE THREAD

**Issue by AdrianAMR** [faktiva/prestashop-clean-urls#66]
Hi :)

If i try to access to `index.php?controller=order-confirmation&id_cart=52` the URL is redirect without params. 

If I print `Tools::getAllValues()` -> return only the name of controller.

![unnamed](https://cloud.githubusercontent.com/assets/15330543/19739824/bb0c1b28-9bbc-11e6-9263-91609878748a.png)

But if i access to the url with seo, `order-confirmation.php?id_cart=52`
and print `Tools::getAllValues()` -> return the param `id_cart` and name of controller.

![image](https://cloud.githubusercontent.com/assets/15330543/19739856/ccf0a282-9bbc-11e6-9f52-4d31bae5f288.png)

Best regards

**Comment by drAlberT** [comment]
Hi,
  thank you for reporting ..

So, if I understand you issue, when the module is active you **have** the QS parameter and you think they shouldn't be there !??

What is the problem if they are present?

Looking for your clarifications

Regards

**Comment by AdrianAMR** [comment]
The problem if i access to the url mydomain.com/index.php?controller=order-confirmation&id_cart=52

The param id_cart isnt present... because if i acces this url, redirect to the SEO URL order-confirmation without params...

**Comment by drAlberT** [comment]
So the scenario is **the opposite** you described in this issue? ...

**Comment by AdrianAMR** [comment]
Yes, the issue is on a route controller, when access mydomain.com/index.php?controller=order-confirmation&id_cart=52&id_module=20 you lost the $_GET parameter id_cart and id_module!

**Comment by drAlberT** [comment]
Ok, thanks.

Will inspect ASAP

**Comment by AdrianAMR** [comment]
In the module Redsys for Payment, when users confirmation the pay are redirect to ugly url(index.php?controller=order-confirmation&id_cart=52). 

I solved changing the ugly url in the module for the pretty url! 

Thanks!!

**Comment by drAlberT** [comment]
You should be able to rewrite the URL in PS backoffice -> `SEO / URLs` .. select the module and write there the "pretty URL" you want the module to use ..

Let me know if it works for you.

**Comment by AdrianAMR** [comment]
The problem is not the url from the module on SEO / URL. 
In the module use directly the code (BASE_URL/index.php?controller=order-confirmation&paramrs...).
I have to change directly on the module where put "index.php?controller=order-confirmation" for the url that the module has on SEO / URL, and this works for me.

Sorry for my English! :)

**Comment by drAlberT** [comment]
Oh .. if the module uses `BASE_URL/index.php?controller=order-confirmation&paramrs...` then it is  its bad. It should use a PS-core helper to build the URL, this way automatically handling the routing change made by use of pretty URLs ..

If you implement a good patch keep the time to submit it to the module author ;)

So, I close this issue as `invalid`, as it is not an issue of this module. Thanks for your time.

Best regards
