### ISSUE TITLE
301 redirect when friendly url (slug) change

### ISSUE THREAD

**Issue by pretoriano80** [faktiva/prestashop-clean-urls#67]
Hi, i have noticed that when you change the url of a product the old url is not redirected to the new one, which is Prestashop's default behavior without this module. 
Obviously this is very bad for SEO because crawlers will find a 404 error instead of 301 redirect. Can you please have a look into this?

**Comment by drAlberT** [comment]
Hi @pretoriano80 .. AFAIK Prestashop did **NOT** behaves as you say .. 

If you have a product with slug "**`product-name`**" and rename it to "**`product-other-name`**" you will **not** have a 301 redirect automagically set by PS from the old "**`ID-product-name`**" to the new "**`ID-other-product-name`**" ..

Are you sure? .. Aren't you referring to the possibility of redirecting a disabled product to do a 301 redirect to another product instead??

Thanks

**Comment by pretoriano80** [comment]
I made a quick test yesterday on a backup site and Prestashop automatically redirected the old link to the new one just like in your example, basically "old_product_name"  was redirected to "new_product_name". 
I had debug mode activated so i could also see Prestashop warning that the page moved. 
I will make another test later when i get home and post the results here.

**Comment by pretoriano80** [comment]
Just finished another test here are the steps and Prestashop behaviour 👍 
NOTE: Don't test this on a production site

1. If you have Clean URLs enabled please disable it or even better,uninstall
2. Make sure Prestashop's default "friendly url" is active and working
3. Modify the "friendly url" of a product and save (in my case was from "gaming_pc" to "gaming_pc_new" )
4. Open the product page using the old link (so in my case was "gaming_pc" )
5. Prestashop will use a 301 redirect to send you to the new url


With Clean Url enabled this will result in a "404 page not found" error and this is bad really bad for SEO and modifying a large amount of products will be very time consuming and hard to manage .

Please let me know if you need further testing or if you need my assistance ,mostly for testing a possible implementation in Clean url (i know for a fact that similar commercial modules are using 301 redirect technics).

**Comment by drAlberT** [comment]
Please report your complete system info:
- PS version
- PHP version
- Apache
- the complete list of your installed modules 

Thanks

**Comment by pretoriano80** [comment]
This are the specs for my test site:

- PrestaShop -1.6.1.9
- PHP - 5.4.45
- Apache - 2.4
- Modules : i use a clean Prestashop installation for testing so only Clean URLs and SEO-TK are enabled but when i tested the redirection with Presta's default "friendly url" both modules and overrides were disabled.

I also had a good read on Prestashop's forum and it looks that this 301 redirect is Prestashop's default behaviour and one of the reason some old respected developers doesn't seem to like "clean urls" modules.I will post a link to the discussion if i manage to find it.

**Comment by pretoriano80** [comment]
Ok,i've found one of the threads that i was reading yesterday about clean urls and 301 redirects by Prestashop engine,here it is: [Link to Prestashop forum](https://www.prestashop.com/forums/topic/489546-the-clean-url-myth/)

**Comment by drAlberT** [comment]
??
 What info should I get from this forum? Nothing new AFAICS

**Comment by pretoriano80** [comment]
That thread just points out that by default Prestashop use 301 redirect when you modify a product url while you said it does not,so clearly Clean URLs module break that functionality .Imho this is an important bug and if it can't be solved at least should be specified in the Read me.

P.S: Don't get me wrong,i understand this is a free module and that you are doing all this for free,so i really appreciate your work.I'm not a developer so the only thing i can do to help improve the module is at least report a bug/issue and offer my help for testing.

**Comment by drAlberT** [comment]
In this thread it is said a clear thing ..  I don't think I never negate it.

**Prestashop DOES NOT perform a 301 redirect FROM old url to NEW one** ... as there is NO data in the backend DB storing this info

  **BUT**

**It simply argues the right page** the user wants **by the ID** being prefixed!!

In other words, you can say that **PS simply IGNORES the URL part after the ID**, so you can write `ID-whateverNonExistentUrlYouWant` and it will automagically just work .. as it will be routed to the right page, the one with the given ID!


**This module scope is to remove the ID from the URL, so it is quite impossible to retain such a behavior.**

Will close as invalid.


Hope you understand the point, **_I'm very grate for the time you spent and for the help you are offering_** :)

Best regards
