### ISSUE TITLE
It doesn't work on PrestaShop 1.7.x

### ISSUE THREAD

**Issue by bestCss01** [faktiva/prestashop-clean-urls#76]
I try the last Release but don't work for prestashop 1.7.04
any suggestions?
the dev website is http://bestcssaward.x10host.com/prestashop/
Thanks!

**Comment by drAlberT** [comment]
the previous one is working instead? .. thnks

**Comment by bestCss01** [comment]
no, don't work.

**Comment by drAlberT** [comment]
so .. it seems the module is not working with PS 1.7 at all 

I never tested it on PS 1.7 so can't say if it should work or not .. . but is PS 1.7 still allowing overrides? If not it will never work in the form it is thought  nowadays

**Comment by bestCss01** [comment]
yes, PS 1.7 allow overrides. I know there are modules that clean url for ps 1.7.04

**Comment by xsbr** [comment]
I tested it with PS **v1.7.0.4** and works fine with all kind of URLs, except **Categories** that returns 404

**Comment by xsbr** [comment]
Some files had folder location changed from PS 1.6 -> 1.7

`.../front/CategoryController.php -> .../front/listing/CategoryController.php
.../front/ManufacturerController.php -> .../front/listing/ManufacturerController.php
.../front/SupplierController.php -> .../front/listing/SupplierController.php`

So during module install PS didn't override this files. I put them manually in **override/controllers/front/listing/** and **Categories** dispatcher works fine.

I don't know how to fix on faktiva_cleanurls.php but I hope it helps.

**Comment by drAlberT** [comment]
@xsbr Great!

Will do ASAP .. Thank you very much!!!

**Comment by francesco-carrella** [comment]
Prestashop 1.7 is the current stable version, it would be really nice to have it working

About the bugs I found:

Category Page isn't working and redirect to:

Product page url contains a ?id_product_attribute=... like:
http://localhost/home/faded-short-sleeves-tshirt?id_product_attribute=1#/1-size-s/13-color-orange

Into Product page the switching between product variant is not woking

**Comment by drAlberT** [comment]
Hi @francesco-carrella,
  Unfortunately this module has been developed to support our own
Prestashop installation, which is still running PS 1.6

As you can see we release this module free of charge, we are not making
business with it .. this doesn't mean we will not support PS 1.7, but it
means we can't assure support on versions we doesn't use because we are not
payed for this.

I'm sorry, but I'll try to handle this request ASAP, can't assure a
deadline.

**Comment by baextroem** [comment]
Any news on fixing this for PS 1.7? I've tried with the trix that @xsbr wrote. This does not work for me thou. I use PrestaShop version: 1.7.1.2

Anyone?

**Comment by xD3VHAX** [comment]
Tested and works with **PS 1.7.2.3**

**Comment by drAlberT** [comment]
@xD3VHAX  It Works as is or you are talking about the proposed "trick" ? .. thanks for reporting.

**Comment by MaxL** [comment]
i think @xD3VHAX hasn't tested with product variants since these still not work. Module only works if you don't use product variants.

**Comment by xD3VHAX** [comment]
Yes sorry does'nt work if product variants is enable.

**Comment by drAlberT** [comment]
Uhmm ok thanks guys ..

Can you confirm it would be fixed moving overrides as per https://github.com/faktiva/prestashop-clean-urls/issues/76#issuecomment-279855827 ?

**Comment by xD3VHAX** [comment]
@drAlberT  No this trick fix only direct access to products but not product variants issue

**Comment by drAlberT** [comment]
uhmm so .. the simple answer is "**this module is not supported on PS 1.7.x**" :)

BTW, both the config and the `.php` main file state a version constraint against Prestashop .. how is it possible it is installed? Any idea? I have no PS 1.7 install for checking

**Comment by MaxL** [comment]
the max constraint is `'max' => _PS_VERSION_`, ;)

**Comment by drAlberT** [comment]
@MaxL my bad .. I set the correct check on master (https://github.com/faktiva/prestashop-clean-urls/blob/master/faktiva_cleanurls.php#L41) but forgot to release it.

Going to release right now

**Comment by drAlberT** [comment]
@MaxL done
