### ISSUE TITLE
I can't install after I uninstalled it

### ISSUE THREAD

**Issue by Fernandomp67** [faktiva/prestashop-clean-urls#77]
Hello. I had to uninstall your module in Prestashop 1.6.1.11 and deleted every file as you explain. 

But now I can't install it again. I have this message (perhaps not exactly, because I have it in spanish):
Unable to install with manual control. The method canonicalRedirection in the class FrontController is already overriden by faktiva_cleanurls version 1.2.1

How could I solve this issue?

**Comment by drAlberT** [comment]
Something is still in the override/* class just remove every reference by hand

**Comment by Fernandomp67** [comment]
Sorry! That was easy. I can install it again. But now it isn't working. id still appears in every route at Seo and URL configuration.

**Comment by drAlberT** [comment]
You should be able tu uninstall and re-install .. if done cleanly it should be ok ..

If still problems please give more details, otherwise will have to close the issue

**Comment by Fernandomp67** [comment]
Hello again. I don´t know exactly what happened, but I unninstall it and some other old modules (I am cleaning my shop) and it´s working know.
Great module. Thanks!
