### ISSUE TITLE
getPaginationLink override conflict

### ISSUE THREAD

**Issue by mrsof** [faktiva/prestashop-clean-urls#80]
Hi,
1st, thx for this module.

I tried to install but I faced off this error : 
Unable to install override : method getPaginationLink in class Link is already overriden.

PS 1.6.1.11
Custom Theme

**Comment by drAlberT** [comment]
Another module you installed have already overridden the same functionalities .. module **not in the core** distribution

**Comment by drAlberT** [comment]
please gimme details, if confirmed I'll close

**Comment by mrsof** [comment]
As I said before it's a custom theme so there is certainly a confilct with modules. I'll post an issue to the developer's module support but for now I don't have more details.

**Comment by drAlberT** [comment]
You can take a look to the overrides/ dir and find the Link.php file ..

**Comment by drAlberT** [comment]
Any news?

**Comment by mrsof** [comment]
I deleted overrides/Link.php file. Then install worked well.
