### ISSUE TITLE
Keyword "{id}" is still required

### ISSUE THREAD

**Issue by hubba1987** [faktiva/prestashop-clean-urls#85]
Hello,

After module installation I go to "SEO and URLs" and try to edit settings like described here, but I'm still getting:
Keyword "{id}" required for route "product_rule" (rule: "{category:/}{rewrite}.html")

Thank you.

**Comment by drAlberT** [comment]
for some reason the module is not working for you .. try cleaning every cache

**Comment by drAlberT** [comment]
@hubba1987 any news ?

**Comment by hubba1987** [comment]
Cleaning cache didn't help ((

**Comment by drAlberT** [comment]
Please give more details.

OS, PS version, other overriding modules installed, a screenshot of your PS configuration for SEO/URL and other pertinent sections  .. as many info you give as easier I'll be able to help you

**Comment by hubba1987** [comment]
Maybe the root cause is PHP version? I have 5.4.13

Sorry, interface in russian, but I think all is understandable.
Info:
![image](https://cloud.githubusercontent.com/assets/20992476/26399678/7bb0fa4c-4086-11e7-9227-42d39ff841de.png)

![image](https://cloud.githubusercontent.com/assets/20992476/26399716/b133ab10-4086-11e7-96aa-2d7675d1c14a.png)

![image](https://cloud.githubusercontent.com/assets/20992476/26399729/bd352402-4086-11e7-8899-ecbf24961eb1.png)

**Comment by drAlberT** [comment]
Is the module correctly installed too? .. add a SS of the modules page plz

Moreover, if it is a PHP version issue you should find some error in your server logs ..

**Comment by hubba1987** [comment]
Modules. 
All others under this are standard modules.
![image](https://cloud.githubusercontent.com/assets/20992476/26400141/43bbbc38-4088-11e7-976e-b418ec4f69bf.png)

**Comment by drAlberT** [comment]
You have another module for the same task already installed !  "Clean URLs" .. remove it, remove mine, clear caches, reinstall mine

Hopefully should work ;)

**Comment by hubba1987** [comment]
It didn't help (

Anyway, thank you for your help! 
I believe search engines will re-index my site soon and I'll be ok with URLs containing ids

**Comment by drAlberT** [comment]
It has to work .. you have for sure some issue in your overrides ..  you should check your overrids dir and remove anything remained pending from old modules

**Comment by hubba1987** [comment]
Ou!
It started to work after I deleted /cache/class_index.php as mentioned in /override/override_readme.txt

I think you should put this information in README.md

**Comment by drAlberT** [comment]
this is a "standard" issue resolution for PS ;)  good to know you are ok now.

Best regards
