### ISSUE TITLE
Errors in prestashop 1.7.2 RC 1

### ISSUE THREAD

**Issue by TecnoHands** [faktiva/prestashop-clean-urls#87]
Hi, I try config in the new prestashop release candidate, but i cant config ok.

In the product link display this
http://localhost/prestashop/es/prueba/producto1?id_product_attribute=0

in the cms category I config only {rewrite} and work ok.
but cant config category, and products url

**Comment by drAlberT** [comment]
PS 1.7.x is not supported for now
