### ISSUE TITLE
Not working With Same URL Products in disabled categories

### ISSUE THREAD

**Issue by prestashoplaurent** [faktiva/prestashop-clean-urls#88]
Hello,

I tried to install your module on Prestashop 1.6.1.15 the both ways :
1) from the module page I added the module, it loaded and then the module cannot be found
2) I uploaded manually into the modules directory and then the module cannot be found from the module page

In the module page I display all modules, your module is not showing so cannot be installed.

**Comment by drAlberT** [comment]
Can't help with this info .. Had a look to your PHP logs? .. I need some debugging info otherwise it's impossible to help

**Comment by prestashoplaurent** [comment]
The module cannot be installed, it's just like if you upload a non installable file.

no error is generated in my log + no error is displayed

I set in the config file debug mode to TRUE but there is no error

For your reference here is a video https://youtu.be/twG0Q9NQS_Q

also I tried on 4 different Prestashop installs and it's the same thing, the module cannot be installed.

**Comment by prestashoplaurent** [comment]
Also not working with Prestashop 1.6.1.14 just tried on a fresh install. - I guess it's not working with all 1.6.1.x

**Comment by drAlberT** [comment]
no, it is online on my shop on PS 1.6.1.13

**Comment by drAlberT** [comment]
You are strong to install an export of the master branch. 

You have to download the release file, not the master

**Comment by prestashoplaurent** [comment]
You are right, my apology.

Installation is working then the module find some products with the same URL (which is not true because it's inside different category so the URL is not the same) + the products are inside disabled category so the products cannot be seen in the front end. I don't want to delete those products, I need them

I cannot use the module in this way. Each time I try to remove the id I get this message :
Keyword "{id}" required for route "product_rule" (rule: "{categories:/}{rewrite}.html")
