### ISSUE TITLE
Problem with product Combinations (PS1.7.x)

### ISSUE THREAD

**Issue by Detys** [faktiva/prestashop-clean-urls#90]
Hello, 

I'm on Prestashop 1.7.1.2 using CleanUrls release 1.2.2
Here is my problem. 
The link generated is correct

/en/resins/wanhao-uv-resin?id_product_attribute=1064#/11-color-black
however (after turning debug on) it is redirected to the default combination
/en/resins/wanhao-uv-resin?id_product_attribute=879

After that clicking on any combination just ignores the selection and adds the '#attribute'
so in this example the url becomes 
/en/resins/wanhao-uv-resin?id_product_attribute=879#/16-color-yellow

Therefore combinations are broken. Any suggestions?

**Comment by drAlberT** [comment]
As said PS 1.7 is not supported, sorry
