### ISSUE TITLE
Problem with ps 1.7.2.2

### ISSUE THREAD

**Issue by SimmacoMe** [faktiva/prestashop-clean-urls#93]
when i try to config module i sow this 
![cattura](https://user-images.githubusercontent.com/32878947/31678209-b12cc444-b36d-11e7-86f7-02effdd05ac1.PNG)
how can i fix this problem? i deleted all file in module description

**Comment by drAlberT** [comment]
It should be only a warning .. it is trying to check if you have duplicated routes .. donno why values are empty anyway

**Comment by drAlberT** [comment]
The module ha no parameter to be configure, it should be safe to just ignore it

**Comment by SimmacoMe** [comment]
i can't press anything thera are 565 problem

**Comment by SimmacoMe** [comment]
who is the file how drow the product url?

**Comment by SimmacoMe** [comment]
this is my override folder 
![cattura](https://user-images.githubusercontent.com/32878947/31680488-bd798460-b374-11e7-9cae-0fe35d71bbf6.PNG)
i think i have problem right?

**Comment by drAlberT** [comment]
you have multiple languages / shops using the same URL in different scopes for the same product.
You have nothing to press .. simply go ahead and leave the module page (click on the menù and go away)...

Are you experiencing some other "real" issue making you think you are in trouble?

**Comment by SimmacoMe** [comment]
i don't understend how can i fix this problem. in my shops are installed 2 language but the english are disable. i have disable all url module (seo and yours) and i sow discrepancy from product path and result see 
![cattura2](https://user-images.githubusercontent.com/32878947/31706019-c848b604-b3e7-11e7-9e02-6b4f1f4804bb.jpg)
this image 
I think that some file ( genereting product path) are corrupt. if i know it position i can restore with the original file ad i done.

**Comment by SimmacoMe** [comment]
what do you think about this set? 
![cattura](https://user-images.githubusercontent.com/32878947/31725557-eeeae16e-b424-11e7-852c-6b0147b77839.PNG)
