### ISSUE TITLE
Module Fabulous but No Products shown under subcategory

### ISSUE THREAD

**Issue by marcixargh** [faktiva/prestashop-clean-urls#95]
Hello everybody,

First of all I have to thank you for this module. it works great!
The only think is that now if i access the products through the main category --> sub-category --> product i can not find it . They are gone.

On the other side, if I put in the product specific url in the browser , it finds the product. How can I solve this or why is it so ?

Thank you a lot and all the best,

Marcello

**Comment by drAlberT** [comment]
Hi,
 plz provide more info on your configuration and Seo/Url settings

**Comment by drAlberT** [comment]
@marcixargh ping
